# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

development: &default
  adapter: postgresql
  database: hypertorrentapi_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 5
  timeout: 5000

docker:
  adapter: postgresql
  encoding: unicode
  database: hypertorrentapi_docker
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: hypertorrent-api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: hypertorrentapi_production


# default: &default
#   adapter: postgresql
#   encoding: utf8
#   host: localhost
#   min_messages: warning
#   pool: 5
#   timeout: 5000
#   min_messages: warning

# development:
#   <<: *default
#   database: torrent_api_development

# test:
#   <<: *default
#   database: torrent_api_test

# docker:
#   adapter: postgresql
#   encoding: unicode
#   database: torrent_api_docker
#   pool: 5
#   username: postgres
#   password:
#   host: db

# production:
#   <<: *default
#   database: <%= ENV['DATABASE'] %>
#   user: <%= ENV['DATABASE_USER'] %>
#   port: 5432
#   password: <%= ENV['DATABASE_PASSWORD'] %>
